apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: ui
  namespace: ui
  labels:
    app: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      initContainers:
        - name: init-container
          image: busybox:1.28
          command: ['sh', '-c', 'until nslookup load-balancer-ui; do echo waiting for load-balancer-ui; sleep 60; done;']
      containers:
      - name: ui
        image: junjie3617/webapp-frontend:latest
        ports:
        - name: live-port
          containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
      imagePullSecrets:
      - name: registrykey
