---
- hosts: localhost
  connection: local
  environment:
    - AWS_REGION: "{{ aws_region }}"
    - NAME: "{{ namespace }}"
    - KOPS_STATE_STORE: s3://{{namespace}}
    - AWS_PROFILE: "{{profile}}"
    
  tasks:
    - import_role:
        name: roles/delete-cluster
        # name: roles/delete-rds