---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend2db
  namespace: backend
  labels:
    app: backend2db
spec:
  replicas: {{ .Values.replicaCount }}
  minReadySeconds: 15
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: backend2db
  template:
    metadata:
      labels:
        app: backend2db
      annotations: 
    spec:
      containers:
      - name: backend2db
        image: {{ .Values.imageBackend }}
        imagePullPolicy: Always
        env:
          - name: database_url
            valueFrom: 
              configMapKeyRef:
                name: {{ .Release.Name }}-configmap-backend2db
                key: db_url
        ports:
          - name: live-port
            containerPort: 8080
