apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-load-balancer-backend2db
  namespace: backend
spec:
  selector:
    app: backend2db
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer