apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-load-balancer-backend
  namespace: backend
spec:
  selector:
    app: backend
  ports:
    - port: 8081
      targetPort: 8081
  type: LoadBalancer