# Default values for mychart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
imageBackend: junjie3617/webapp-backend:a8c9f6a3249d51c15018dd2b04d5c1bb5fa3c4b5
imageFrontend: varadjoshi89/demo:latest
backendUrl: localhost
databaseUrl: db1.cz6gapqsisar.us-east-1.rds.amazonaws.com
bucketUrl: webapp-csye7374
imagePullSecrets: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImFuVnVhbWxsTXpZeE56cElSV3AxYm1wcFpURXlNekF3TUE9PSIKCQl9Cgl9LAoJIkh0dHBIZWFkZXJzIjogewoJCSJVc2VyLUFnZW50IjogIkRvY2tlci1DbGllbnQvMTkuMDMuNSAoZGFyd2luKSIKCX0sCgkiZXhwZXJpbWVudGFsIjogImRpc2FibGVkIiwKCSJzdGFja09yY2hlc3RyYXRvciI6ICJzd2FybSIKfQ==

redis:
  password: "password"
redisPort: 6379
initContainers:
  name: busybox:1.28
